app:
  env: "dev"
  port: 8080
  debug: true
  log_level: "debug"

db:
  host: "127.0.0.1"
  user: ""
  password: ""
  port: 5433
  dbname: "redhat"
  sslmode: "disable"

secure:
  jwt:
    private_key_base64: ""
    public_key_base64: ""
    access_expiration_min: 720  # 12 hours

steam:
  api_key: ""
  app_id: 0
